### ISSUE TITLE
J'suis pas content

### ISSUE THREAD

**Issue by Reiko69420** [XoMeDa69/JNAWeb#1]
1. **NAN MAIS OH IL ESTO U LE J S OU QUIOI LA ERUH IL MANQUE LE JS**

**Comment by XoMeDa69** [comment]
TU FERME TA GEULE ET TU APRECCIE

**Comment by Reiko69420** [comment]
Ok pardon

**Comment by XoMeDa69** [comment]
C'ETS PAS TON CODE
